# Generated by Django 4.1.1 on 2022-09-25 08:04

import api.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import lib.log_changes_mixin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.JSONField(blank=True, null=True)),
                ('to_user', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '聊天記錄',
                'verbose_name_plural': '聊天記錄',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='職業名稱')),
            ],
            options={
                'verbose_name': '職業',
                'verbose_name_plural': '職業',
            },
            bases=(lib.log_changes_mixin.LogChangesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='KeyValueStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('value', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('updated_at', api.models.AutoDateTimeField(default=django.utils.timezone.now, verbose_name='修改日期')),
            ],
        ),
        migrations.CreateModel(
            name='LiffAppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(max_length=255, verbose_name='Channel種類')),
                ('name', models.CharField(max_length=255, verbose_name='LIFF 名稱')),
                ('liff_id', models.CharField(db_index=True, max_length=255, verbose_name='LIFF ID')),
                ('content_hash', models.CharField(default='', max_length=255, verbose_name='內容 hash 值')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('updated_at', api.models.AutoDateTimeField(default=django.utils.timezone.now, verbose_name='修改日期')),
            ],
            options={
                'verbose_name': 'LIFF APP 設定',
                'verbose_name_plural': 'LIFF APP 設定',
            },
        ),
        migrations.CreateModel(
            name='LineBotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='姓名/別名')),
                ('picture_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='顯圖網址')),
                ('line_uid', models.CharField(db_index=True, default='', max_length=255, verbose_name='Line UID')),
                ('phone_number', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='手機')),
                ('user_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='玩家類型')),
                ('following', models.BooleanField(default=False, verbose_name='有追蹤本頻道')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('updated_at', api.models.AutoDateTimeField(default=django.utils.timezone.now, verbose_name='修改日期')),
            ],
            options={
                'verbose_name': 'LINE使用者',
                'verbose_name_plural': 'LINE使用者',
            },
            bases=(lib.log_changes_mixin.LogChangesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RichMenuSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Menu 名稱')),
                ('menu_id', models.CharField(db_index=True, max_length=255, verbose_name='Menu ID')),
                ('content_hash', models.CharField(default='', max_length=255, verbose_name='內容 hash 值')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('updated_at', api.models.AutoDateTimeField(default=django.utils.timezone.now, verbose_name='修改日期')),
            ],
            options={
                'verbose_name': 'Rich Menu 設定',
                'verbose_name_plural': 'Rich Menu 設定',
            },
        ),
        migrations.CreateModel(
            name='QueuedLineMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(blank=True, null=True, verbose_name='內容')),
                ('extra_info', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('bot_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.linebotuser')),
            ],
            options={
                'verbose_name': '待發的Line訊息',
                'verbose_name_plural': '待發的Line訊息',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(blank=True, max_length=16, null=True, verbose_name='暱稱')),
                ('money', models.IntegerField(default=0, verbose_name='金錢')),
                ('diamond', models.IntegerField(default=0, verbose_name='鑽石')),
                ('daily_request_done', models.BooleanField(default=False, verbose_name='已簽到')),
                ('job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.job')),
                ('line_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.linebotuser')),
            ],
            options={
                'verbose_name': '玩家',
                'verbose_name_plural': '玩家',
            },
            bases=(lib.log_changes_mixin.LogChangesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, db_index=True, max_length=255)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bot_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.linebotuser')),
            ],
        ),
        migrations.AddField(
            model_name='linebotuser',
            name='active_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.richmenusetting'),
        ),
        migrations.AddIndex(
            model_name='liffappsetting',
            index=models.Index(fields=['channel_type', 'name'], name='api_liffapp_channel_c2c5db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='liffappsetting',
            unique_together={('channel_type', 'name')},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='bot_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.linebotuser'),
        ),
    ]
